name: 🚀 Feature request
description: Suggest an idea for this project
labels:
  - enhancement
body:
  - type: checkboxes
    attributes:
      label: Self Check
      description: Please check these items before submitting
      options:
        - label: This is only for feature request, if you would like to ask a question, please head to [Discussions](https://github.com/bnb-chain/example-hub/discussions/categories/general).
          required: true
        - label: I have searched for existing feature requests [search for existing feature requests](https://github.com/bnb-chain/example-hub/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement), including closed ones.
          required: true
        - label: I will use English to describe the feature request
          required: true
  - type: textarea
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Please describe your proposed solution
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Please describe any alternative solutions you've considered
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add any other context about the feature request here.
    validations:
      required: false
